import { solve } from './sugoroku';

describe.each([
    [[true, true, false, true], 2],
    [[true, false, true, false, true, true, false, true], 3],
    [[true, false, false, false, true, true, true, true], 0],
    [[true], 1],
    [
        [
            true,
            true,
            false,
            false,
            true,
            false,
            true,
            false,
            true,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            true,
            false,
            true,
            true,
        ],
        0,
    ],
    [
        [
            true,
            true,
            true,
            true,
            false,
            false,
            true,
            true,
            false,
            false,
            true,
            true,
            true,
            true,
            false,
            true,
            false,
            true,
            false,
            true,
            false,
            false,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            false,
            false,
            true,
            false,
            false,
            true,
            false,
            true,
            false,
            true,
            false,
            true,
            true,
            false,
            false,
            true,
        ],
        480,
    ],
])('solve', (path: boolean[], expected: number) => {
    it(`path: ${JSON.stringify(path)}`, () => {
        const actual = solve(path);
        expect(actual).toBe(expected);
    });
});
